services:
  traefik:
    image: traefik:v3.0
    container_name: traefik
    restart: always
    networks:
      - proxy
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/traefik.yml:/traefik.yml:ro
      - ./traefik/configs:/configs:ro
      - ./traefik/logs:/logs:rw
    environment:
      - TZ=America/Chicago
      - VAULT_TOKEN=${VAULT_TOKEN}
    read_only: true
    security_opt:
      - no-new-privileges=true
    labels:
      - traefik.enable=true
      - traefik.http.routers.traefik-https.entrypoints=https
      - traefik.http.routers.traefik-https.rule=Host(`dashboard.homelab.cantina`)
      - traefik.http.middlewares.traefik-auth.basicauth.users=${ADMIN_AUTH}
      - traefik.http.routers.traefik-https.middlewares=traefik-auth
      - traefik.http.routers.traefik-https.service=api@internal
      - traefik.http.routers.traefik-https.tls.certresolver=vault
      - traefik.http.routers.traefik-https.tls.certresolver.vault.vault.auth.token=${VAULT_TOKEN}
      - traefik.http.routers.traefik-https.tls.domains[0].main=homelab.cantina
      - traefik.http.routers.traefik-https.tls.domains[0].sans=*.homelab.cantina
